module.exports = {
  // mode: 'jit',
  purge: ['./pages/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      keyframes: {
        'spinner-one': {
          '0%': { opacity: 1 },
          '12%': { opacity: 1 },
          '25%': { opacity: 1 },
          '36%': { opacity: 1 },
          '49%': { opacity: 0 },
          '61%': { opacity: 0 },
          '74%': { opacity: 0 },
          '86%': { opacity: 0 },
          '99%': { opacity: 0 },
        },
        'spinner-two': {
          '0%': { opacity: 0 },
          '12%': { opacity: 1 },
          '25%': { opacity: 1 },
          '36%': { opacity: 1 },
          '49%': { opacity: 1 },
          '61%': { opacity: 0 },
          '74%': { opacity: 0 },
          '86%': { opacity: 0 },
          '99%': { opacity: 0 },
        },
        'spinner-three': {
          '0%': { opacity: 0 },
          '12%': { opacity: 0 },
          '25%': { opacity: 1 },
          '36%': { opacity: 1 },
          '49%': { opacity: 1 },
          '61%': { opacity: 1 },
          '74%': { opacity: 0 },
          '86%': { opacity: 0 },
          '99%': { opacity: 0 },
        },
        'spinner-four': {
          '0%': { opacity: 0 },
          '12%': { opacity: 0 },
          '25%': { opacity: 0 },
          '36%': { opacity: 1 },
          '49%': { opacity: 1 },
          '61%': { opacity: 1 },
          '74%': { opacity: 1 },
          '86%': { opacity: 0 },
          '99%': { opacity: 0 },
        },
        'spinner-five': {
          '0%': { opacity: 0 },
          '12%': { opacity: 0 },
          '25%': { opacity: 0 },
          '36%': { opacity: 0 },
          '49%': { opacity: 1 },
          '61%': { opacity: 1 },
          '74%': { opacity: 1 },
          '86%': { opacity: 1 },
          '99%': { opacity: 0 },
        },
      },
      animation: {
        'spinner-one': 'spinner-one 1s infinite',
        'spinner-two': 'spinner-two 1s infinite',
        'spinner-three': 'spinner-three 1s infinite',
        'spinner-four': 'spinner-four 1s infinite',
        'spinner-five': 'spinner-five 1s infinite',
      },
    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
};
